name: Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the latest available Python 3 version

    - name: Run all tests from tester.py
      run: |
        python -m unittest discover -s ./ -p 'tester.py'

