name: Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install flake8
        python -m pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 .
        echo Error: Process completed with exit code 1.
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.9.20/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.20/x64/lib

    - name: Run unit tests with coverage report
      run: |
        coverage run -m unittest discover -s ./ -p 'test_*.py'
        coverage report -m

